import { User } from '@/types/auth';
import { Room } from '@/types/room';
import { Guest } from '@/types/guest';
import { Booking } from '@/types/booking';
import { Payment, Invoice } from '@/types/payment';
import { Staff, ActivityLog } from '@/types/staff';
import { Notification } from '@/types/notification';

// Mock Users
export const mockUsers: User[] = [
  {
    id: '1',
    email: 'admin@grandhotel.com',
    name: 'John Administrator',
    role: 'admin',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=admin',
    createdAt: '2023-01-15T10:00:00Z',
    lastLogin: '2024-01-20T08:30:00Z',
    isActive: true,
  },
  {
    id: '2',
    email: 'manager@grandhotel.com',
    name: 'Sarah Manager',
    role: 'manager',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=manager',
    createdAt: '2023-03-10T14:00:00Z',
    lastLogin: '2024-01-20T09:15:00Z',
    isActive: true,
  },
  {
    id: '3',
    email: 'reception@grandhotel.com',
    name: 'Mike Receptionist',
    role: 'receptionist',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=reception',
    createdAt: '2023-06-20T11:00:00Z',
    lastLogin: '2024-01-20T07:00:00Z',
    isActive: true,
  },
];

// Mock Rooms
export const mockRooms: Room[] = [
  {
    id: '1',
    roomNumber: '101',
    type: 'standard',
    floor: 1,
    pricePerNight: 120,
    status: 'available',
    maxOccupancy: 2,
    amenities: ['WiFi', 'TV', 'Air Conditioning', 'Mini Bar'],
    description: 'Cozy standard room with city view',
    lastCleaned: '2024-01-20T06:00:00Z',
  },
  {
    id: '2',
    roomNumber: '102',
    type: 'standard',
    floor: 1,
    pricePerNight: 120,
    status: 'occupied',
    maxOccupancy: 2,
    amenities: ['WiFi', 'TV', 'Air Conditioning', 'Mini Bar'],
    description: 'Cozy standard room with garden view',
    currentBookingId: '1',
  },
  {
    id: '3',
    roomNumber: '201',
    type: 'deluxe',
    floor: 2,
    pricePerNight: 180,
    status: 'available',
    maxOccupancy: 3,
    amenities: ['WiFi', 'TV', 'Air Conditioning', 'Mini Bar', 'Balcony', 'Coffee Machine'],
    description: 'Spacious deluxe room with mountain view',
    lastCleaned: '2024-01-20T07:30:00Z',
  },
  {
    id: '4',
    roomNumber: '202',
    type: 'deluxe',
    floor: 2,
    pricePerNight: 180,
    status: 'cleaning',
    maxOccupancy: 3,
    amenities: ['WiFi', 'TV', 'Air Conditioning', 'Mini Bar', 'Balcony', 'Coffee Machine'],
    description: 'Spacious deluxe room with pool view',
  },
  {
    id: '5',
    roomNumber: '301',
    type: 'suite',
    floor: 3,
    pricePerNight: 350,
    status: 'occupied',
    maxOccupancy: 4,
    amenities: ['WiFi', 'TV', 'Air Conditioning', 'Mini Bar', 'Balcony', 'Coffee Machine', 'Jacuzzi', 'Living Room'],
    description: 'Luxurious suite with panoramic views',
    currentBookingId: '2',
  },
  {
    id: '6',
    roomNumber: '302',
    type: 'suite',
    floor: 3,
    pricePerNight: 350,
    status: 'available',
    maxOccupancy: 4,
    amenities: ['WiFi', 'TV', 'Air Conditioning', 'Mini Bar', 'Balcony', 'Coffee Machine', 'Jacuzzi', 'Living Room'],
    description: 'Elegant suite with separate dining area',
    lastCleaned: '2024-01-19T15:00:00Z',
  },
  {
    id: '7',
    roomNumber: '401',
    type: 'presidential',
    floor: 4,
    pricePerNight: 800,
    status: 'maintenance',
    maxOccupancy: 6,
    amenities: ['WiFi', 'TV', 'Air Conditioning', 'Mini Bar', 'Private Terrace', 'Butler Service', 'Jacuzzi', 'Private Pool', 'Kitchen'],
    description: 'The ultimate luxury experience with private pool and butler service',
  },
  {
    id: '8',
    roomNumber: '103',
    type: 'standard',
    floor: 1,
    pricePerNight: 120,
    status: 'available',
    maxOccupancy: 2,
    amenities: ['WiFi', 'TV', 'Air Conditioning', 'Mini Bar'],
    description: 'Standard room with accessible features',
    lastCleaned: '2024-01-20T08:00:00Z',
  },
];

// Mock Guests
export const mockGuests: Guest[] = [
  {
    id: '1',
    firstName: 'Emma',
    lastName: 'Thompson',
    email: 'emma.thompson@email.com',
    phone: '+1 555-0101',
    address: '123 Oak Street',
    city: 'New York',
    country: 'USA',
    idType: 'passport',
    idNumber: 'US123456789',
    dateOfBirth: '1985-03-15',
    nationality: 'American',
    vipStatus: true,
    createdAt: '2023-06-10T14:00:00Z',
    updatedAt: '2024-01-15T10:00:00Z',
    totalBookings: 8,
    totalSpent: 4850,
  },
  {
    id: '2',
    firstName: 'James',
    lastName: 'Wilson',
    email: 'james.wilson@email.com',
    phone: '+44 20 7946 0958',
    address: '45 Baker Street',
    city: 'London',
    country: 'UK',
    idType: 'passport',
    idNumber: 'GB987654321',
    dateOfBirth: '1978-07-22',
    nationality: 'British',
    vipStatus: false,
    createdAt: '2023-08-20T09:00:00Z',
    updatedAt: '2024-01-18T16:00:00Z',
    totalBookings: 3,
    totalSpent: 1890,
  },
  {
    id: '3',
    firstName: 'Sophie',
    lastName: 'Martinez',
    email: 'sophie.martinez@email.com',
    phone: '+34 612 345 678',
    address: 'Calle Mayor 78',
    city: 'Madrid',
    country: 'Spain',
    idType: 'national_id',
    idNumber: 'ES12345678X',
    dateOfBirth: '1990-11-30',
    nationality: 'Spanish',
    vipStatus: false,
    createdAt: '2023-11-05T11:00:00Z',
    updatedAt: '2024-01-10T14:00:00Z',
    totalBookings: 2,
    totalSpent: 720,
  },
  {
    id: '4',
    firstName: 'Alexander',
    lastName: 'Petrov',
    email: 'alex.petrov@email.com',
    phone: '+49 170 123 4567',
    address: 'Friedrichstraße 123',
    city: 'Berlin',
    country: 'Germany',
    idType: 'passport',
    idNumber: 'DE456789012',
    dateOfBirth: '1982-05-18',
    nationality: 'German',
    vipStatus: true,
    createdAt: '2023-04-15T08:00:00Z',
    updatedAt: '2024-01-19T12:00:00Z',
    totalBookings: 12,
    totalSpent: 9500,
  },
];

// Get today's date for realistic booking data
const today = new Date();
const formatDate = (date: Date) => date.toISOString().split('T')[0];

// Mock Bookings
export const mockBookings: Booking[] = [
  {
    id: '1',
    guestId: '1',
    roomId: '2',
    checkInDate: formatDate(new Date(today.getTime() - 2 * 24 * 60 * 60 * 1000)),
    checkOutDate: formatDate(new Date(today.getTime() + 3 * 24 * 60 * 60 * 1000)),
    status: 'checked-in',
    paymentStatus: 'paid',
    totalAmount: 600,
    paidAmount: 600,
    numberOfGuests: 2,
    specialRequests: 'Late check-out requested',
    createdAt: '2024-01-15T10:00:00Z',
    updatedAt: '2024-01-18T14:00:00Z',
  },
  {
    id: '2',
    guestId: '4',
    roomId: '5',
    checkInDate: formatDate(new Date(today.getTime() - 1 * 24 * 60 * 60 * 1000)),
    checkOutDate: formatDate(new Date(today.getTime() + 5 * 24 * 60 * 60 * 1000)),
    status: 'checked-in',
    paymentStatus: 'partial',
    totalAmount: 2100,
    paidAmount: 1000,
    numberOfGuests: 3,
    specialRequests: 'Anniversary celebration - please arrange champagne',
    createdAt: '2024-01-10T16:00:00Z',
    updatedAt: '2024-01-19T10:00:00Z',
  },
  {
    id: '3',
    guestId: '2',
    roomId: '3',
    checkInDate: formatDate(today),
    checkOutDate: formatDate(new Date(today.getTime() + 2 * 24 * 60 * 60 * 1000)),
    status: 'reserved',
    paymentStatus: 'pending',
    totalAmount: 360,
    paidAmount: 0,
    numberOfGuests: 2,
    createdAt: '2024-01-18T11:00:00Z',
    updatedAt: '2024-01-18T11:00:00Z',
  },
  {
    id: '4',
    guestId: '3',
    roomId: '1',
    checkInDate: formatDate(new Date(today.getTime() + 1 * 24 * 60 * 60 * 1000)),
    checkOutDate: formatDate(new Date(today.getTime() + 4 * 24 * 60 * 60 * 1000)),
    status: 'reserved',
    paymentStatus: 'paid',
    totalAmount: 360,
    paidAmount: 360,
    numberOfGuests: 1,
    createdAt: '2024-01-19T09:00:00Z',
    updatedAt: '2024-01-19T09:00:00Z',
  },
  {
    id: '5',
    guestId: '1',
    roomId: '6',
    checkInDate: formatDate(new Date(today.getTime() - 10 * 24 * 60 * 60 * 1000)),
    checkOutDate: formatDate(new Date(today.getTime() - 7 * 24 * 60 * 60 * 1000)),
    status: 'checked-out',
    paymentStatus: 'paid',
    totalAmount: 1050,
    paidAmount: 1050,
    numberOfGuests: 4,
    createdAt: '2024-01-05T14:00:00Z',
    updatedAt: '2024-01-13T11:00:00Z',
  },
];

// Mock Payments
export const mockPayments: Payment[] = [
  {
    id: '1',
    bookingId: '1',
    guestId: '1',
    amount: 600,
    method: 'card',
    type: 'booking',
    status: 'completed',
    transactionId: 'TXN-2024-001',
    createdAt: '2024-01-15T10:30:00Z',
    processedAt: '2024-01-15T10:31:00Z',
    processedBy: '3',
  },
  {
    id: '2',
    bookingId: '2',
    guestId: '4',
    amount: 1000,
    method: 'online',
    type: 'deposit',
    status: 'completed',
    transactionId: 'TXN-2024-002',
    createdAt: '2024-01-10T16:30:00Z',
    processedAt: '2024-01-10T16:32:00Z',
    processedBy: '2',
  },
  {
    id: '3',
    bookingId: '4',
    guestId: '3',
    amount: 360,
    method: 'card',
    type: 'booking',
    status: 'completed',
    transactionId: 'TXN-2024-003',
    createdAt: '2024-01-19T09:15:00Z',
    processedAt: '2024-01-19T09:16:00Z',
    processedBy: '3',
  },
  {
    id: '4',
    bookingId: '5',
    guestId: '1',
    amount: 1050,
    method: 'cash',
    type: 'booking',
    status: 'completed',
    transactionId: 'TXN-2024-004',
    createdAt: '2024-01-13T11:00:00Z',
    processedAt: '2024-01-13T11:00:00Z',
    processedBy: '3',
  },
];

// Mock Invoices
export const mockInvoices: Invoice[] = [
  {
    id: '1',
    bookingId: '1',
    guestId: '1',
    invoiceNumber: 'INV-2024-0001',
    items: [
      { description: 'Room 102 - Standard (5 nights)', quantity: 5, unitPrice: 120, total: 600 },
    ],
    subtotal: 600,
    tax: 72,
    total: 672,
    status: 'paid',
    dueDate: '2024-01-20',
    createdAt: '2024-01-15T10:00:00Z',
    paidAt: '2024-01-15T10:31:00Z',
  },
  {
    id: '2',
    bookingId: '2',
    guestId: '4',
    invoiceNumber: 'INV-2024-0002',
    items: [
      { description: 'Room 301 - Suite (6 nights)', quantity: 6, unitPrice: 350, total: 2100 },
      { description: 'Champagne Service', quantity: 1, unitPrice: 150, total: 150 },
    ],
    subtotal: 2250,
    tax: 270,
    total: 2520,
    status: 'sent',
    dueDate: formatDate(new Date(today.getTime() + 5 * 24 * 60 * 60 * 1000)),
    createdAt: '2024-01-10T16:00:00Z',
  },
];

// Mock Staff
export const mockStaff: Staff[] = [
  {
    id: '1',
    userId: '1',
    name: 'John Administrator',
    email: 'admin@grandhotel.com',
    phone: '+1 555-0001',
    role: 'admin',
    department: 'Administration',
    hireDate: '2020-01-15',
    isActive: true,
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=admin',
    address: '456 Executive Lane',
    permissions: ['all'],
    createdAt: '2020-01-15T10:00:00Z',
    updatedAt: '2024-01-01T10:00:00Z',
  },
  {
    id: '2',
    userId: '2',
    name: 'Sarah Manager',
    email: 'manager@grandhotel.com',
    phone: '+1 555-0002',
    role: 'manager',
    department: 'Operations',
    hireDate: '2021-03-10',
    isActive: true,
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=manager',
    permissions: ['bookings.manage', 'rooms.manage', 'guests.manage', 'payments.view', 'reports.view'],
    createdAt: '2021-03-10T10:00:00Z',
    updatedAt: '2024-01-15T10:00:00Z',
  },
  {
    id: '3',
    userId: '3',
    name: 'Mike Receptionist',
    email: 'reception@grandhotel.com',
    phone: '+1 555-0003',
    role: 'receptionist',
    department: 'Front Desk',
    hireDate: '2022-06-20',
    isActive: true,
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=reception',
    permissions: ['bookings.create', 'bookings.view', 'guests.create', 'guests.view', 'rooms.view'],
    createdAt: '2022-06-20T10:00:00Z',
    updatedAt: '2024-01-10T10:00:00Z',
  },
];

// Mock Activity Logs
export const mockActivityLogs: ActivityLog[] = [
  {
    id: '1',
    staffId: '3',
    action: 'check_in',
    entityType: 'booking',
    entityId: '1',
    details: 'Guest Emma Thompson checked in to Room 102',
    createdAt: '2024-01-18T14:00:00Z',
  },
  {
    id: '2',
    staffId: '2',
    action: 'payment_received',
    entityType: 'payment',
    entityId: '2',
    details: 'Received deposit of $1,000 for booking #2',
    createdAt: '2024-01-10T16:32:00Z',
  },
  {
    id: '3',
    staffId: '3',
    action: 'booking_created',
    entityType: 'booking',
    entityId: '3',
    details: 'New reservation created for James Wilson',
    createdAt: '2024-01-18T11:00:00Z',
  },
];

// Mock Notifications
export const mockNotifications: Notification[] = [
  {
    id: '1',
    type: 'warning',
    category: 'booking',
    title: 'Late Check-out Request',
    message: 'Room 102 has requested a late check-out. Please confirm availability.',
    isRead: false,
    actionUrl: '/bookings/1',
    createdAt: new Date(today.getTime() - 30 * 60 * 1000).toISOString(),
  },
  {
    id: '2',
    type: 'info',
    category: 'booking',
    title: 'Upcoming Check-in',
    message: 'James Wilson is scheduled to check in today at Room 201.',
    isRead: false,
    actionUrl: '/bookings/3',
    createdAt: new Date(today.getTime() - 2 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '3',
    type: 'warning',
    category: 'payment',
    title: 'Pending Payment',
    message: 'Booking #2 has a pending balance of $1,100. Follow up required.',
    isRead: true,
    actionUrl: '/payments',
    createdAt: new Date(today.getTime() - 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '4',
    type: 'error',
    category: 'room',
    title: 'Maintenance Required',
    message: 'Room 401 is under maintenance. Expected completion: 2 days.',
    isRead: true,
    actionUrl: '/rooms/7',
    createdAt: new Date(today.getTime() - 48 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '5',
    type: 'success',
    category: 'guest',
    title: 'VIP Guest Arriving',
    message: 'VIP guest Alexander Petrov checked in. Ensure premium service.',
    isRead: true,
    actionUrl: '/guests/4',
    createdAt: new Date(today.getTime() - 24 * 60 * 60 * 1000).toISOString(),
  },
];
